module.exports = [
    {
        "city": "Mumbai",
        "state": "Maharashtra",
        "latitude": 19.076,
        "longitude": 72.8777,
        "title": "Forest Retreat",
        "description": "Camp by the river with fresh air and picturesque views.",
        "price": 34,
    },
    {
        "city": "Delhi",
        "state": "Delhi",
        "latitude": 28.6139,
        "longitude": 77.209,
        "title": "Maple Woods",
        "description": "Perfect for hikers and nature lovers, surrounded by tall pines.",
        "price": 40,
    },
    {
        "city": "Bengaluru",
        "state": "Karnataka",
        "latitude": 12.9716,
        "longitude": 77.5946,
        "title": "Dusty Trails",
        "description": "Escape into nature with serene surroundings and starry skies.",
        "price": 42,
    },
    {
        "city": "Hyderabad",
        "state": "Telangana",
        "latitude": 17.385,
        "longitude": 78.4867,
        "title": "Maple Woods",
        "description": "Escape into nature with serene surroundings and starry skies.",
        "price": 15,
    },
    {
        "city": "Ahmedabad",
        "state": "Gujarat",
        "latitude": 23.0225,
        "longitude": 72.5714,
        "title": "Redwood Base",
        "description": "Perfect for hikers and nature lovers, surrounded by tall pines.",
        "price": 41,
    },
    {
        "city": "Chennai",
        "state": "Tamil Nadu",
        "latitude": 13.0827,
        "longitude": 80.2707,
        "title": "Maple Woods",
        "description": "Escape into nature with serene surroundings and starry skies.",
        "price": 23,
    },
    {
        "city": "Kolkata",
        "state": "West Bengal",
        "latitude": 22.5726,
        "longitude": 88.3639,
        "title": "Ancient Camp",
        "description": "Enjoy the tranquility of the hills with your loved ones.",
        "price": 38,
    },
    {
        "city": "Pune",
        "state": "Maharashtra",
        "latitude": 18.5204,
        "longitude": 73.8567,
        "title": "Misty Valley",
        "description": "Camp by the river with fresh air and picturesque views.",
        "price": 20,
    },
    {
        "city": "Jaipur",
        "state": "Rajasthan",
        "latitude": 26.9124,
        "longitude": 75.7873,
        "title": "Maple Woods",
        "description": "Escape into nature with serene surroundings and starry skies.",
        "price": 22,
    },
    {
        "city": "Lucknow",
        "state": "Uttar Pradesh",
        "latitude": 26.8467,
        "longitude": 80.9462,
        "title": "Dusty Trails",
        "description": "Unplug and recharge in this peaceful forest campground.",
        "price": 44,
    },
    {
        "city": "Bhopal",
        "state": "Madhya Pradesh",
        "latitude": 23.2599,
        "longitude": 77.4126,
        "title": "Ocean Breeze Camp",
        "description": "Camp by the river with fresh air and picturesque views.",
        "price": 10,
    },
    {
        "city": "Chandigarh",
        "state": "Punjab/Haryana",
        "latitude": 30.7333,
        "longitude": 76.7794,
        "title": "Forest Retreat",
        "description": "Perfect for hikers and nature lovers, surrounded by tall pines.",
        "price": 47,
    },
    {
        "city": "Shimla",
        "state": "Himachal Pradesh",
        "latitude": 31.1048,
        "longitude": 77.1734,
        "title": "Misty Valley",
        "description": "Unplug and recharge in this peaceful forest campground.",
        "price": 32,
    },
    {
        "city": "Manali",
        "state": "Himachal Pradesh",
        "latitude": 32.2396,
        "longitude": 77.1887,
        "title": "Skyview Escape",
        "description": "Unplug and recharge in this peaceful forest campground.",
        "price": 23,
    },
    {
        "city": "Darjeeling",
        "state": "West Bengal",
        "latitude": 27.036,
        "longitude": 88.2627,
        "title": "Ancient Camp",
        "description": "Unplug and recharge in this peaceful forest campground.",
        "price": 38,
    },
    {
        "city": "Goa",
        "state": "Goa",
        "latitude": 15.2993,
        "longitude": 74.124,
        "title": "Skyview Escape",
        "description": "Enjoy the tranquility of the hills with your loved ones.",
        "price": 38,
    },
    {
        "city": "Rishikesh",
        "state": "Uttarakhand",
        "latitude": 30.0869,
        "longitude": 78.2676,
        "title": "Ancient Camp",
        "description": "Escape into nature with serene surroundings and starry skies.",
        "price": 26,
    },
    {
        "city": "Varanasi",
        "state": "Uttar Pradesh",
        "latitude": 25.3176,
        "longitude": 82.9739,
        "title": "Redwood Base",
        "description": "Perfect for hikers and nature lovers, surrounded by tall pines.",
        "price": 23,
    },
    {
        "city": "Srinagar",
        "state": "Jammu and Kashmir",
        "latitude": 34.0837,
        "longitude": 74.7973,
        "title": "Forest Retreat",
        "description": "Escape into nature with serene surroundings and starry skies.",
        "price": 22,
    },
    {
        "city": "Leh",
        "state": "Ladakh",
        "latitude": 34.1526,
        "longitude": 77.5771,
        "title": "Dusty Trails",
        "description": "Enjoy the tranquility of the hills with your loved ones.",
        "price": 39,
    }
];